import "./globals.css";
import type { Metadata } from "next";
import { Roboto, Azeret_Mono, Outfit } from "next/font/google";
import localFont from "next/font/local";
import styles from "./layout.module.css";
import Nav from "./components/Nav/Nav";
import Footer from "./components/Footer/Footer";
import { Toaster } from "react-hot-toast";

// const roboto = Roboto({
//   weight: ["400", "500"],
//   style: ["normal"],
//   subsets: ["latin"],
//   variable: "--roboto",
// });

// const bebasneue = localFont({
//   src: "../../public/fonts/bebasneue.woff2",
//   variable: "--bebasneue",
// });

const azeretMono = Azeret_Mono({
  weight: ["400", "500"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--azeretMono",
});

const outfit = Outfit({
  weight: ["400", "500"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--outfit",
});

export const metadata: Metadata = {
  title: "Chris Ware Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${outfit.variable} ${azeretMono.variable} ${styles.layout}`}
      >
        <Toaster
          position='top-right'
          toastOptions={{
            className: "toastFont",
          }}
        />
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
